---
title: "visreg_demo"
author: "Jordan Watson"
date: "June 30, 2017"
output: 
  pdf_document: 
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(visreg)
library(reshape2)
library(gridExtra)
library(cowplot) # for the function get_legend
library(mgcv)
```


```{r visreg}
set.seed(2) ## simulate some data... 
dat <- gamSim(1,n=400,dist="normal",scale=2)

dat$y1 <- rbinom(400,1,0.7)

b <- gam(y1~s(x0,x1) + s(x2,x3) + s(f) + s(f0) + s(f1),data=dat,family=binomial)

#  Plot the first bivariate smoother
visreg2d(b,"x0","x1",scale="response")

#  visreg2d creates a list that includes a z field which is a matrix, same as expand.grid.
p1 <- visreg2d(b,"x0","x1",scale="response")

#  Here's what the structure of p1 looks like.
#> str(p1)
#List of 6
#$ x    : num [1:99] 0.00711 0.01722 0.02733 0.03744 0.04754 ...
#$ y    : num [1:99] 0.000663 0.010853 0.021043 0.031233 0.041423 ...
#$ z    : num [1:99, 1:99] 2.22e-16 2.22e-16 2.22e-16 2.22e-16 2.22e-16 ...
#$ n    : num 1
#$ zname: chr "y1"
#$ cond :'data.frame':	1 obs. of  5 variables:
#	..$ x2: num 0.496
#..$ x3: num 0.522
#..$ f : num 7.5
#..$ f0: num 1.26
#..$ f1: num 2.87

#  I couldn't figure out how to customize visreg2d.
#  So I just extract the data, melting the matrix p1$z into a df. Then use expand.grid to add the axes
myp1 <- ggplot(melt(p1$z) %>% 
				dplyr::select(value) %>% 
				bind_cols(expand.grid(x=p1$x,y=p1$y)),
			aes(x,y,fill=value)) + 
	geom_tile()+
	scale_fill_distiller(palette = "Spectral") + 
	theme_classic() + 
	labs(x=expression(Delta*distance[subsequent]),y=expression(Delta*distance[previous])) + 
	theme(legend.position="none")

p2 <- visreg2d(b,"x2","x3",scale="response")
#  Make the figure, including a legend
myp2 <- ggplot(melt(p2$z) %>% dplyr::select(value) %>% bind_cols(expand.grid(x=p2$x,y=p2$y)),aes(x,y,fill=value)) + 
	geom_tile()+
	theme_classic() + 
	scale_fill_distiller(palette = "Spectral",name="p(Fishing)") + 
	labs(y=expression(Speed[t+1]),x=expression(Speed[t-1]))

#  Extract the legend using cowplot
legend <- get_legend(myp2)

#  Drop the legend from myp2
myp2 <- myp2 + theme(legend.position="none")

p3 <- visreg(b,"f",gg=TRUE,scale="response") + 
	theme_classic() + 
	ylab("p(Fishing)") + 
	xlab("Distance")
p4 <- visreg(b,"f0",gg=TRUE,scale="response") + 
	theme_classic() + 
	ylab("p(Fishing)") + 
	xlab("Depth")
p5 <- visreg(b,"f1",gg=TRUE,scale="response")  + 
	scale_x_continuous(breaks=seq(0,24,by=6),labels=seq(0,24,by=6)) + 
	theme_classic() + 
	ylab("p(Fishing)") + 
	xlab("Hour")

grid.arrange(myp1,myp2,legend,p3,p4,p5)
```